version: 2

sources:
  - name: bronze
    database: warehouse
    tables:
      - name: raw_yahoo_finance
        meta:
          dagster:
            asset_key: ["bronze_raw_yahoo_finance"]
  - name: gold
    database: analytics
    tables:
      - name: gold__monitor_stock
        meta:
          dagster:
            asset_key: ["gold_monitor_stock"]
